# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://veloclubcirois.github.io/'
baseurl: ''
title: Vélo Club Cirois
description: 'This is my new website'
permalink: pretty
# logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"
logo: "/assets/logos/logo_VCC_couleur.png"
email: veloclubcirois@gmail.com

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Accueil
  url: /
- title: A propos
  url: /about/
- title: Contact
  url: /contact/
- title: Organisations
  url: /organisations/

# Footer nav
navigation_footer:
- title: Retour en haut
  url: "#top"

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "Nos pensées et idées"
    feature_image: "/assets/img/Nuit_du_Therain_2024.png"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
